repos:
- repo: local
  hooks:
    - id: isort
      name: isort
      entry: python -m isort
      language: system
      types: [python]
    - id: black
      name: black
      entry: python -m black
      language: system
      types: [python]
    - id: mypy
      name: mypy
      entry: python -m mypy
      language: system
      types: [python]
    - id: flake8
      name: flake8
      entry: python -m flake8
      language: system
      types: [python]
    - id: clang-format
      name: clang-format
      entry: clang-format
      language: system
      types_or: [c, c++]
