[tool.poetry]
name = "pybind11_stubgen"
version = "0.1.0"
description = "A package that generates python stub files for pybind11 modules."
license = "Apache-2.0"
authors = ["Eric Chang <pkerichang@gmail.com>"]
packages = [
    { include = "pybind11_stubgen", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
