[build-system]
requires = ["poetry_core>=1.0.0", "wheel"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pybind11_utils"
version = "1.0.0"
description = "Python utilties for building pybind11 extensions."
license = "Apache-2.0"
authors = ["Eric Chang <info@bcanalog.com>"]
readme = "README.md"
packages = [
    { include = "pybind11_utils", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.7"
packaging = ">=20"
setuptools = ">=46"
